name: weather_today_app
description: "weather_today - Weather App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  http: ^1.5.0
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/weather_today.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # web:
  #   generate: true
  #   image_path: "assets/icons/weather_today.jpg"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  # windows:
  #   generate: true
  #   image_path: "assets/icons/weather_today.jpg"
  #   icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "assets/icons/weather_today.jpg"